#!/bin/bash
# Create a new personal git repository and connect to GitHub

GITHUB_USERNAME=$(git config user.name)

if [ -z "$GITHUB_USERNAME" ]; then
    echo "Exiting: git username not found. Please ensure you've set your git \
username with\n  git config --global user.name \"your_github_username\""; exit;
fi

if [ -z "$GITHUB_TOKEN" ]; then
    echo "Exiting: GitHub token not found. Please ensure this script has \
access to a token in some way, notably by setting \$GITHUB_USER in your shell's \
startup script (e.g., .zshrc, .bashrc, etc.)"; exit;
fi

# check cmd line args; go to directory
if [ $# -eq 0 ]; then
    while true; do
        read -p "No path supplied... Would you like to use the current directory? [y/n]: " RESPONSE
        case $RESPONSE in
            [Yy]* ) break;;
            [Nn]* ) echo ""; echo "Usage: gh-setup <path-to-repo-directory>"; exit;;
            * ) echo "Please answer Y or N.";;
        esac
    done

    # set title of GitHub repo
    while true; do
        CURRENT_DIR_TITLE=$(basename "$PWD")
        read -p "Use current directory title ($CURRENT_DIR_TITLE) as title of GitHub repository? [y/n]: " RESPONSE
        case $RESPONSE in
            [Yy]* ) USER_REPO_NAME="$CURRENT_DIR_TITLE"; break;;
            [Nn]* ) echo ""; read -p "Enter repository title to use: " USER_REPO_NAME; break;;
            * ) echo "Please answer Y or N.";;
        esac
    done
else
    if [ ! -d "$1" ]; then
        mkdir $1 && cd $1
    else
        cd $1
    fi
    
    DIR_TITLE_FROM_SUPPLIED_PATH=$(basename "$1")
    while true; do
        read -p "Use $DIR_TITLE_FROM_SUPPLIED_PATH as title of GitHub repository? [y/n]: " RESPONSE
        case $RESPONSE in
            [Yy]* ) USER_REPO_NAME="$DIR_TITLE_FROM_SUPPLIED_PATH"; break;;
            [Nn]* ) echo ""; read -p "Enter the title of the git/GitHub repository: " USER_REPO_NAME; break;;
            * ) echo "Please answer Y or N.";;
        esac
    done
fi

REPO_MANUALLY_CREATED=false

manuallyCreateRepo () {
    REPO_MANUALLY_CREATED=true
    while true; do
        read -p "Would you like to manually create the GitHub repository? [y/n]: " RESPONSE
        case $RESPONSE in
            [Yy]* ) 
                echo ""
                echo "Create a new GitHub repository at github.com/$GITHUB_USERNAME with title "$USER_REPO_NAME". Press return when you have completed this step."
                read; break;;
            [Nn]* ) echo ""; echo "Exiting..."; exit;;
            * ) echo "Please answer Y or N.";;
        esac
    done
}

# create GitHub repository
if [[ $(python3 --version) != "Python 3."* ]]; then
    # if Python3 not installed, user can perform manual Github repository creation.
    echo "Dependency \"Python3\" not installed..."
    manuallyCreateRepo

else # Python3 is available, so pip3 is also available
    # Even though Python3 is available, check if version is compatible with PyGithub
    if (( $(echo "$(python3 --version | cut -c 10-) < 6" | bc -l) )); then
        # version requirements per https://pypi.org/project/PyGithub/ on 12/10/21
        echo "Python version $(python3 --version | cut -c 8-) is incompatible with PyGithub. Please use Python 3.6 or above to utilize PyGithub functionality."
        manuallyCreateRepo
    else
        # make sure module PyGithub is installed
        if [ "$(pip3 list | grep -o "PyGithub")" != "PyGithub" ]; then
            echo "Dependency \`PyGithub\` not installed: attempting to install with pip3..."
            pip3 install PyGithub
            echo ""

            if [ "$(pip3 list | grep -o "PyGithub")" != "PyGithub" ]; then
                echo "Dependency \`PyGithub\` could not be installed..."
                manuallyCreateRepo
            fi
        fi

        if [ "$REPO_MANUALLY_CREATED" = false ]; then
            # Create GitHub repo using PyGithub
            RETURNED_REPO_NAME=$(python3 -c "from github import Github
import sys
g = Github('$GITHUB_TOKEN')
user = g.get_user()
repo = user.create_repo('$USER_REPO_NAME')
sys.exit(repo.name)" 2>&1 > /dev/null) # weird indentation is to run python properly

            # here would be the place to check if the return status of the
            # python script returned 0, indicating a successful repository
            # creation. But, because we need to capture the name of the repo,
            # we assume the repository was created successfully. An unfortunate
            # tradeoff.
        fi
    fi
fi

# if the repository was manually created, we need to get the name of the actual
# repository, which may be different from what the user entered, because of how
# GitHub replaces characters (i.e., spaces for dashes). This is done for us
# when the repository is created for us, as we already have a link to the repo.
# The way we do this isn't perfect, but works most of the time. We search for
# the name of the repository from the user's repositories and return the result
if [ "$REPO_MANUALLY_CREATED" = true ]; then
    RETURNED_REPO_NAME=$(python3 -c "from github import Github
import sys
g = Github('$GITHUB_TOKEN')
repos = g.search_repositories(query='$USER_REPO_NAME in:name user:$GITHUB_USERNAME')
for repo in repos:
    sys.exit(repo.name)" 2>&1 > /dev/null) # weird indentation is to run python properly
fi

# create git repository, README.md, and .gitignore
echo ""
git init
echo ""

echo "# $RETURNED_REPO_NAME" >> README.md

GITIGNORE_CREATED=true
# .gitignores from https://github.com/github/gitignore
case "$OSTYPE" in
    darwin*) echo "# General
.DS_Store
.AppleDouble
.LSOverride

Icon[\r]

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk" >> .gitignore;; 
    linux*) echo "*~

# temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*

# KDE directory preferences
.directory

# Linux trash folder which might appear on any partition or disk
.Trash-*

# .nfs files are created when an open file is removed but is still being accessed
.nfs*" >> .gitignore;;
    msys|cygwin*) echo "# Windows thumbnail cache files
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db

# Dump file
*.stackdump

# Folder config file
[Dd]esktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Installer files
*.cab
*.msi
*.msix
*.msm
*.msp

# Windows shortcuts
*.lnk" >> .gitignore;;
    *) echo ".gitignore not created: UNKNOWN: $OSTYPE"; GITIGNORE_CREATED=false;;
esac

if [ "$GITIGNORE_CREATED" = false ]; then
    git add README.md
else
    git add README.md .gitignore
fi

# link local git repository to created GitHub repository and push initial files
git commit -m "First commit (auto-generated by \`gh-setup\` with <3)"
git branch -M main

git remote add origin https://github.com/$GITHUB_USERNAME/$RETURNED_REPO_NAME.git
git push -u origin main

echo "" && echo "[Process Complete] Repo available at https://github.com/$GITHUB_USERNAME/$RETURNED_REPO_NAME"
